#include <stddef.h>
#include "TcpIp_cfg.h"


// This file is autogenerated, any hand modifications will be lost!



const TcpIpGeneralCfgType TcpIpGeneralConfigs = {
	.mainfn_period_ms = 100,
	.tcpip_buffer_mem = 1500
};

const TcpIpLocalAddr TcpIpLocalAddrConfigs[MAX_TCPIP_LOCAL_ADDRESS] = {
	{
		/* TcpIp local address - 0 */
		.addr_id = 0,
		.domain_type = TCPIP_AF_INET,
		.addr_type = TCPIP_UNICAST,
		.addr_assn_life = TCPIP_FORGET,
		.addr_assn_method = TCPIP_STATIC,
		.addr_assn_prio = 1,
		.addr_assn_trig = TCPIP_MANUAL,
		.ip_addr = {192, 168, 3, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		.ip_netmask = {255, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
		.ip_dfroutr = {192, 168, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
	}
};


const TcpIp_ConfigType TcpIp_Config = {
	.gen = &TcpIpGeneralConfigs,
	.local_addr = &TcpIpLocalAddrConfigs
};

